collection:
  COLLECTION_PATH: null
  COLLECTION_PLAYLISTS: false
  COLLECTION_PLAYLISTS_REMAINDER: folder
  COPY_PLAYLISTS: []
  COPY_PLAYLISTS_DESTINATION: null
  PLATFORM: rekordbox
  SHUFFLE_PLAYLISTS: []
configs:
  LOG_LEVEL: INFO
  VERBOSITY: 0
spotify:
  REDDIT_CLIENT_ID: ''
  REDDIT_CLIENT_SECRET: ''
  REDDIT_USER_AGENT: ''
  SPOTIFY_CLIENT_ID: ''
  SPOTIFY_CLIENT_SECRET: ''
  SPOTIFY_PLAYLISTS: false
  SPOTIFY_PLAYLIST_DEFAULT_LIMIT: 50
  SPOTIFY_PLAYLIST_DEFAULT_PERIOD: week
  SPOTIFY_PLAYLIST_DEFAULT_TYPE: hot
  SPOTIFY_PLAYLIST_FROM_UPLOAD: false
  SPOTIFY_PLAYLIST_FUZZ_RATIO: 70
  SPOTIFY_PLAYLIST_POST_LIMIT: 100
  SPOTIFY_PLAYLIST_SUBREDDITS: []
  SPOTIFY_REDIRECT_URI: ''
  SPOTIFY_USERNAME: ''
sync:
  ARTIST_FIRST: false
  AWS_PROFILE: default
  AWS_USE_DATE_MODIFIED: false
  DISCORD_URL: ''
  DOWNLOAD_COLLECTION: false
  DOWNLOAD_EXCLUDE_DIRS: []
  DOWNLOAD_INCLUDE_DIRS: []
  DOWNLOAD_MUSIC: false
  DOWNLOAD_SPOTIFY_PLAYLIST: ''
  DRYRUN: false
  IMPORT_USER: ''
  UPLOAD_COLLECTION: false
  UPLOAD_EXCLUDE_DIRS: []
  UPLOAD_INCLUDE_DIRS: []
  UPLOAD_MUSIC: false
  USB_PATH: null
  USER: ''
utils:
  CHECK_TRACKS: false
  CHECK_TRACKS_FUZZ_RATIO: 80
  CHECK_TRACKS_LOCAL_DIRS: []
  CHECK_TRACKS_SPOTIFY_PLAYLISTS: []
  URL_DOWNLOAD: ''
  URL_DOWNLOAD_DESTINATION: null
