configs:
  AWS_PROFILE: 'default'
  LOG_LEVEL: INFO
  VERBOSITY: 0
  XML_PATH: ''
rekordbox:
  COPY_PLAYLISTS: []
  COPY_PLAYLISTS_DESTINATION: ''
  PURE_GENRE_PLAYLISTS: []
  RANDOMIZE_PLAYLISTS: []
  REKORDBOX_PLAYLISTS: false
  REKORDBOX_PLAYLISTS_REMAINDER: folder
spotify:
  AUTO_PLAYLIST_DEFAULT_LIMIT: 50
  AUTO_PLAYLIST_DEFAULT_PERIOD: week
  AUTO_PLAYLIST_DEFAULT_TYPE: hot
  AUTO_PLAYLIST_FUZZ_RATIO: 70
  AUTO_PLAYLIST_POST_LIMIT: 100
  AUTO_PLAYLIST_SUBREDDITS: []
  AUTO_PLAYLIST_UPDATE: false
  PLAYLIST_FROM_UPLOAD: false
  REDDIT_CLIENT_ID: ''
  REDDIT_CLIENT_SECRET: ''
  REDDIT_USER_AGENT: ''
  SPOTIFY_CLIENT_ID: ''
  SPOTIFY_CLIENT_SECRET: ''
  SPOTIFY_REDIRECT_URI: ''
  SPOTIFY_USERNAME: ''
sync:
  AWS_USE_DATE_MODIFIED: false
  DISCORD_URL: ''
  DOWNLOAD_EXCLUDE_DIRS: []
  DOWNLOAD_INCLUDE_DIRS: []
  DOWNLOAD_MUSIC: false
  DOWNLOAD_SPOTIFY: ''
  DOWNLOAD_XML: false
  DRYRUN: false
  IMPORT_USER: ''
  UPLOAD_EXCLUDE_DIRS: []
  UPLOAD_INCLUDE_DIRS: []
  UPLOAD_MUSIC: false
  UPLOAD_XML: false
  USB_PATH: ''
  USER: ''
utils:
  CHECK_TRACKS: false
  CHECK_TRACKS_FUZZ_RATIO: 80
  CHECK_TRACKS_LOCAL_DIRS: []
  CHECK_TRACKS_SPOTIFY_PLAYLISTS: []
  URL_DOWNLOAD: ''
  URL_DOWNLOAD_DESTINATION: ''
